
- name: Disable Node.js module using ansible.builtin.command
  hosts: backend
  become: yes

  tasks:
    - name: Disable Node.js module
      ansible.builtin.command: dnf module disable nodejs -y


    - name: enable node js
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install Node.js
      ansible.builtin.package:
        name: nodejs
        state: present


    - name: Ensure the user 'expense' is present
      ansible.builtin.user:
        name: expense
        state: present   

    - name: Ensure /app directory exists
      ansible.builtin.file:
        path: /app
        state: directory  
    - name: Download the expense backend zip file
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip 

    - name: Unzip the backend.zip file
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes    


    - name: Import schema from SQL file
      community.mysql.mysql_db:
        name: all
        state: import
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        host: mysql.daws83s.shop    

      

    