
- name: Disable Node.js module using ansible.builtin.command
  hosts: backend
  become: yes

  tasks:
    - name: Disable Node.js module
      ansible.builtin.command: dnf module disable nodejs -y


    - name: enable node js
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install Node.js
      ansible.builtin.package:
        name: nodejs
        state: present


    - name: Ensure the user 'expense' is present
      ansible.builtin.user:
        name: expense
        state: present   

    - name: Ensure /app directory exists
      ansible.builtin.file:
        path: /app
        state: directory     
      

    