
- name: Install MySQL server
  hosts: mysql
  become: yes

  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present
    - name: Install PyMySQL
      ansible.builtin.pip:
        name: PyMySQL
        state: present

    - name: Enable mysqld service
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started 

    
             

    - name: Get MySQL server version
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql.daws83s.shop
      ignore_errors: true  
      register: mysql_info

    - name: printing
      ansible.builtin.debug:
        msg: "{{mysql_info}}"   

    - name: password adding
      ansible.builtin.command:   "mysql_secure_installation --set-root-pass ExpenseApp@1"
      when: mysql_info.failed is true 

