
- name: Install MySQL server
  hosts: mysql
  become: yes

  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: Enable mysqld service
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started 

    - name: Get MySQL server version
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
      register: mysql_info