
- name: Install MySQL server
  hosts: mysql
  become: yes

  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: ansible to install pymysql
      ansible.builtin.pip:
      name:
      - PyMySQL
      executable: pip3.9    

    - name: Enable mysqld service
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started 

    
             

    - name: Get MySQL server version
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysqldaws83s.shop
      ignore_errors: true  
      register: mysql_info